### ISSUE TITLE
Steps for the analysis

### ISSUE THREAD

**Issue by timyerg** [wckdouglas/diffexpr#8]
Hello!
Thank you for Python implementation of DESeq2 tool. I am new to this kind of analysis and now a little bit confused: is a result from cell 4 in a notebook example indentical to the results in cell 7? Are the results from cell 4 in the example sufficient or it is necessary to run cells 5-7? 
And another question: I would like to analyse the effect of 5 treatments versus control and my plan is to run it in the loop for each treatment versus control and get a table with p-values for each run (treatment) in the loop. Is it a right approach or I should somehow run everything together and modify (how?) this line in the code: `dds.get_deseq_result(contrast = ['sample','B','A'])` by adding more levels? Currently I am running it like this:

```
    dds = py_DESeq2(count_matrix = df,
               design_matrix = sample_df,
               design_formula = '~ Treatment',
               gene_column = 'ID') # <- telling DESeq2 this should be the gene ID column

    dds.run_deseq()
    for trt in range(2,7):
      dds.get_deseq_result(contrast = ['Treatment','Trt1','Trt'+str(trt)]) #Trt1 is a control
      res = dds.deseq_result 
      display(res.head())  
```
​Is it a right approach?

**Comment by wckdouglas** [comment]
Hi @timyerg, sorry it took me a while to see this in my inbox! 

>  is a result from cell 4 in a notebook example identical to the results in cell 7?

The `log2foldChange` column should be [different](https://rdrr.io/bioc/DESeq2/man/lfcShrink.html) in cell 7, since lower expression genes can introduce large fold changes and fold change shrinkage should be [useful](https://support.bioconductor.org/p/77461/#77466) in some cases for [visualization and ranking](http://bioconductor.org/packages/devel/bioc/vignettes/DESeq2/inst/doc/DESeq2.html#log-fold-change-shrinkage-for-visualization-and-ranking).

here's a good video about [log fold change shrinkage](https://www.youtube.com/watch?v=ZyRT1z1Sz3g)

> Are the results from cell 4 in the example sufficient or it is necessary to run cells 5-7?

It really depends what your end goal is, but again I think cell 5, 7 is more like for heatmaps and other [visualizations/prioritizing genes](http://bioconductor.org/packages/devel/bioc/vignettes/DESeq2/inst/doc/DESeq2.html#log-fold-change-shrinkage-for-visualization-and-ranking)

> ​Is it a right approach?

yes, I think this is reasonable

but in any case, I'd encourage you to read the [DESeq2 manual for more detail](http://bioconductor.org/packages/devel/bioc/vignettes/DESeq2/inst/doc/DESeq2.html)

**Comment by timyerg** [comment]
Ok, thank you for the clarification!
Now it is clear for me.
And thank you again for porting this tool to the Python. That's really great.
